#!/bin/bash

# BRAMHI Framework - .claude Folder Validation Script
# Version: 1.0.0
# Last Updated: January 7, 2026
# Owner: BRAMHI_LABS
#
# Usage: ./verify_claude.sh [--strict] [--fix]
#   --strict: Fail on warnings (default: fail only on errors)
#   --fix: Attempt to fix missing files by creating stubs

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
ERRORS=0
WARNINGS=0
PASSED=0

# Flags
STRICT_MODE=false
FIX_MODE=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --strict)
            STRICT_MODE=true
            ;;
        --fix)
            FIX_MODE=true
            ;;
    esac
done

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$CLAUDE_DIR")"

echo ""
echo "=================================================="
echo "  BRAMHI Framework - .claude Validation"
echo "=================================================="
echo ""
echo "Checking: $CLAUDE_DIR"
echo ""

# Function to check if file exists
check_file() {
    local file="$1"
    local required="$2"  # true/false
    local full_path="$CLAUDE_DIR/$file"

    if [ -f "$full_path" ]; then
        echo -e "  ${GREEN}✓${NC} $file"
        ((PASSED++))
        return 0
    else
        if [ "$required" = "true" ]; then
            echo -e "  ${RED}✗${NC} $file (MISSING - REQUIRED)"
            ((ERRORS++))

            if [ "$FIX_MODE" = "true" ]; then
                create_stub "$file"
            fi
        else
            echo -e "  ${YELLOW}!${NC} $file (missing - optional)"
            ((WARNINGS++))
        fi
        return 1
    fi
}

# Function to check if directory exists and has minimum files
check_directory() {
    local dir="$1"
    local min_files="$2"
    local full_path="$CLAUDE_DIR/$dir"

    if [ -d "$full_path" ]; then
        local count=$(find "$full_path" -maxdepth 1 -name "*.md" -o -name "*.yaml" -o -name "*.sh" | wc -l | tr -d ' ')
        if [ "$count" -ge "$min_files" ]; then
            echo -e "  ${GREEN}✓${NC} $dir/ ($count files, min: $min_files)"
            ((PASSED++))
        else
            echo -e "  ${YELLOW}!${NC} $dir/ ($count files, expected: $min_files)"
            ((WARNINGS++))
        fi
    else
        echo -e "  ${RED}✗${NC} $dir/ (MISSING DIRECTORY)"
        ((ERRORS++))

        if [ "$FIX_MODE" = "true" ]; then
            mkdir -p "$full_path"
            echo -e "      ${BLUE}→${NC} Created directory: $dir/"
        fi
    fi
}

# Function to check version header in file
check_version_header() {
    local file="$1"
    local full_path="$CLAUDE_DIR/$file"

    if [ -f "$full_path" ]; then
        if grep -q "^\*\*Version\*\*:" "$full_path" || grep -q "^# Version:" "$full_path"; then
            return 0
        else
            echo -e "  ${YELLOW}!${NC} $file missing Version header"
            ((WARNINGS++))
            return 1
        fi
    fi
    return 1
}

# Function to check freshness (modified within N days)
check_freshness() {
    local file="$1"
    local max_days="$2"
    local full_path="$CLAUDE_DIR/$file"

    if [ -f "$full_path" ]; then
        local mod_time=$(stat -f %m "$full_path" 2>/dev/null || stat -c %Y "$full_path" 2>/dev/null)
        local now=$(date +%s)
        local age_days=$(( (now - mod_time) / 86400 ))

        if [ "$age_days" -le "$max_days" ]; then
            echo -e "  ${GREEN}✓${NC} $file (updated $age_days days ago)"
            return 0
        else
            echo -e "  ${YELLOW}!${NC} $file (last updated $age_days days ago, expected < $max_days)"
            ((WARNINGS++))
            return 1
        fi
    fi
    return 1
}

# Function to create stub file
create_stub() {
    local file="$1"
    local full_path="$CLAUDE_DIR/$file"
    local dir=$(dirname "$full_path")

    # Ensure directory exists
    mkdir -p "$dir"

    # Create stub based on file type
    cat > "$full_path" << EOF
# $(basename "$file" .md)

**Version**: 0.0.1
**Last Updated**: $(date +%Y-%m-%d)
**Owner**: TODO
**Status**: Draft

---

## TODO

This file was auto-generated by verify_claude.sh.
Please fill in the required content.

---

**Document Status**: Stub - requires completion.
EOF

    echo -e "      ${BLUE}→${NC} Created stub: $file"
}

# ============================================
# TIER 1: CORE GOVERNANCE (Required)
# ============================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TIER 1: CORE GOVERNANCE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_file "README.md" true
check_file "MASTER_GUIDE.md" true
check_file "BEST_PRACTICES.md" true
check_file "DOCUMENT_STANDARDS.md" true
check_file "ACCESS_CONTROL.yaml" true
check_file "project.yaml" true

# ============================================
# TIER 2: PROJECT CONTEXT (Required)
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TIER 2: PROJECT CONTEXT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_file "CODEBASE_STRUCTURE.md" true
check_file "DATA_STRUCTURE.md" true
check_file "DOCUMENT_REGISTRY.md" true

# ============================================
# TIER 3: OPERATIONAL (Required)
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TIER 3: OPERATIONAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_file "SESSION_LOG.md" true
check_file "CHANGE_LOG.md" true
check_file "QUICK_START.md" false  # New - may not exist yet
check_file "CLAUDE_CHECKLIST.md" false  # New - may not exist yet
check_file "PERFORMANCE_METRICS.md" false  # New - may not exist yet

# ============================================
# TIER 4: EXECUTION (Required)
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TIER 4: EXECUTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_directory "commands" 10
check_directory "templates" 13

# Check specific command files
echo ""
echo "  Commands:"
for cmd in init bootstrap setup strategy coding testing audit general release-audit close; do
    check_file "commands/$cmd.md" true
done

echo ""
echo "  Sessions:"
check_directory "sessions" 1
check_file "sessions/SESSION_INDEX.md" true
check_file "sessions/SESSION_PROTOCOL.md" false

# ============================================
# TIER 5: FRAMEWORK (Required for standardization)
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TIER 5: BRAMHI FRAMEWORK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_directory "bramhi" 4
check_file "bramhi/BRAMHI_MASTER_PLAN.md" true
check_file "bramhi/CANONICAL_STRUCTURE.md" true
check_file "bramhi/UNIFIED_CHECKLIST.md" true
check_file "bramhi/KPI_SCHEMA.md" true
check_file "bramhi/verify_claude.sh" true

# ============================================
# VERSION HEADER CHECKS
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VERSION HEADERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

for file in README.md MASTER_GUIDE.md BEST_PRACTICES.md DOCUMENT_STANDARDS.md; do
    check_version_header "$file"
done

# ============================================
# FRESHNESS CHECKS
# ============================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "FRESHNESS (Last 7 days)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

check_freshness "SESSION_LOG.md" 7
check_freshness "CHANGE_LOG.md" 7
check_freshness "sessions/SESSION_INDEX.md" 7

# ============================================
# SUMMARY
# ============================================
echo ""
echo "=================================================="
echo "  VALIDATION SUMMARY"
echo "=================================================="
echo ""
echo -e "  ${GREEN}Passed:${NC}   $PASSED"
echo -e "  ${YELLOW}Warnings:${NC} $WARNINGS"
echo -e "  ${RED}Errors:${NC}   $ERRORS"
echo ""

# Calculate compliance percentage
TOTAL=$((PASSED + WARNINGS + ERRORS))
if [ "$TOTAL" -gt 0 ]; then
    COMPLIANCE=$(( (PASSED * 100) / TOTAL ))
    echo "  Compliance: $COMPLIANCE%"
else
    echo "  Compliance: N/A"
fi

echo ""

# Exit code based on results
if [ "$ERRORS" -gt 0 ]; then
    echo -e "${RED}✗ VALIDATION FAILED${NC}"
    echo "  Fix $ERRORS error(s) before proceeding."
    echo ""
    exit 1
elif [ "$WARNINGS" -gt 0 ] && [ "$STRICT_MODE" = "true" ]; then
    echo -e "${YELLOW}✗ VALIDATION FAILED (strict mode)${NC}"
    echo "  Fix $WARNINGS warning(s) before proceeding."
    echo ""
    exit 1
else
    echo -e "${GREEN}✓ VALIDATION PASSED${NC}"
    if [ "$WARNINGS" -gt 0 ]; then
        echo "  Note: $WARNINGS warning(s) found - consider addressing."
    fi
    echo ""
    exit 0
fi
